/**
 * Design Tokens Template
 *
 * This file is auto-injected into every generated project to ensure
 * consistent, high-quality design patterns. Used by the AI generation
 * to create beautiful, non-generic UIs.
 */

export const DESIGN_TOKENS_TEMPLATE = `/**
 * Design System Tokens
 * Auto-generated by KripTik AI - Premium UI patterns
 */

export const tokens = {
  // ==========================================================================
  // COLOR PALETTE
  // ==========================================================================
  colors: {
    // Primary gradient (amber to orange - for CTAs and highlights)
    primary: {
      from: '#fbbf24', // amber-400
      to: '#f97316',   // orange-500
      gradient: 'linear-gradient(135deg, #fbbf24 0%, #f97316 100%)',
    },

    // Background colors (dark, atmospheric)
    background: {
      base: '#0a0a0f',      // Deep dark
      elevated: '#0f0f14',  // Slightly lighter
      surface: '#1a1a24',   // Card backgrounds
    },

    // Surface colors (with transparency for glassmorphism)
    surface: {
      glass: 'rgba(30, 30, 40, 0.5)',
      card: 'rgba(26, 26, 36, 0.8)',
      overlay: 'rgba(0, 0, 0, 0.6)',
    },

    // Text colors
    text: {
      primary: '#ffffff',
      secondary: '#94a3b8',   // slate-400
      muted: '#64748b',       // slate-500
      inverse: '#0a0a0f',
    },

    // Accent colors (semantic)
    accent: {
      success: '#10b981', // emerald-500
      warning: '#f59e0b', // amber-500
      error: '#ef4444',   // red-500
      info: '#06b6d4',    // cyan-500
    },

    // Border colors
    border: {
      subtle: 'rgba(255, 255, 255, 0.1)',
      default: 'rgba(255, 255, 255, 0.15)',
      focus: 'rgba(251, 191, 36, 0.5)', // amber with transparency
    },
  },

  // ==========================================================================
  // SHADOWS
  // ==========================================================================
  shadows: {
    // Colored glows
    glow: {
      primary: '0 8px 32px rgba(251, 191, 36, 0.15)',
      success: '0 8px 32px rgba(16, 185, 129, 0.15)',
      error: '0 8px 32px rgba(239, 68, 68, 0.15)',
    },

    // Card shadows
    card: {
      default: '0 4px 6px -1px rgba(0, 0, 0, 0.3), 0 2px 4px -2px rgba(0, 0, 0, 0.2)',
      hover: '0 20px 25px -5px rgba(0, 0, 0, 0.4), 0 8px 10px -6px rgba(0, 0, 0, 0.3)',
      elevated: '0 25px 50px -12px rgba(0, 0, 0, 0.5)',
    },

    // Glass effect shadow
    glass: '0 4px 30px rgba(0, 0, 0, 0.2)',
  },

  // ==========================================================================
  // TYPOGRAPHY
  // ==========================================================================
  typography: {
    // Font families
    fonts: {
      heading: "'Inter', 'system-ui', sans-serif",
      body: "'Inter', 'system-ui', sans-serif",
      mono: "'JetBrains Mono', 'Fira Code', monospace",
    },

    // Font sizes with line heights
    sizes: {
      xs: { size: '0.75rem', lineHeight: '1rem' },
      sm: { size: '0.875rem', lineHeight: '1.25rem' },
      base: { size: '1rem', lineHeight: '1.5rem' },
      lg: { size: '1.125rem', lineHeight: '1.75rem' },
      xl: { size: '1.25rem', lineHeight: '1.75rem' },
      '2xl': { size: '1.5rem', lineHeight: '2rem' },
      '3xl': { size: '1.875rem', lineHeight: '2.25rem' },
      '4xl': { size: '2.25rem', lineHeight: '2.5rem' },
      '5xl': { size: '3rem', lineHeight: '1.2' },
    },

    // Font weights
    weights: {
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
  },

  // ==========================================================================
  // SPACING & SIZING
  // ==========================================================================
  spacing: {
    xs: '0.25rem',   // 4px
    sm: '0.5rem',    // 8px
    md: '1rem',      // 16px
    lg: '1.5rem',    // 24px
    xl: '2rem',      // 32px
    '2xl': '3rem',   // 48px
    '3xl': '4rem',   // 64px
  },

  // ==========================================================================
  // BORDER RADIUS
  // ==========================================================================
  borderRadius: {
    sm: '0.375rem',  // 6px
    md: '0.5rem',    // 8px
    lg: '0.75rem',   // 12px
    xl: '1rem',      // 16px
    '2xl': '1.5rem', // 24px
    full: '9999px',
  },

  // ==========================================================================
  // ANIMATIONS
  // ==========================================================================
  animations: {
    // Durations
    duration: {
      fast: '150ms',
      normal: '200ms',
      slow: '300ms',
      slower: '500ms',
    },

    // Easings
    easing: {
      default: 'cubic-bezier(0.4, 0, 0.2, 1)',
      in: 'cubic-bezier(0.4, 0, 1, 1)',
      out: 'cubic-bezier(0, 0, 0.2, 1)',
      inOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
      bounce: 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
    },

    // Framer Motion variants
    variants: {
      fadeIn: {
        initial: { opacity: 0 },
        animate: { opacity: 1 },
        transition: { duration: 0.3 },
      },
      slideUp: {
        initial: { opacity: 0, y: 20 },
        animate: { opacity: 1, y: 0 },
        transition: { duration: 0.3 },
      },
      staggerContainer: {
        animate: {
          transition: { staggerChildren: 0.1 },
        },
      },
      hover: {
        scale: 1.02,
        y: -2,
        transition: { duration: 0.2 },
      },
      tap: {
        scale: 0.98,
      },
    },
  },

  // ==========================================================================
  // Z-INDEX SCALE
  // ==========================================================================
  zIndex: {
    base: 0,
    dropdown: 10,
    sticky: 20,
    modal: 30,
    popover: 40,
    toast: 50,
  },
};

// ==========================================================================
// TAILWIND CLASS PATTERNS
// ==========================================================================
export const patterns = {
  // Card styles
  card: {
    base: 'rounded-2xl bg-slate-900/50 backdrop-blur-xl border border-white/10',
    hover: 'hover:border-amber-500/50 hover:shadow-xl hover:shadow-amber-500/10 transition-all duration-300',
    gradient: 'bg-gradient-to-br from-slate-900/80 to-slate-950/80',
  },

  // Button styles
  button: {
    primary: 'px-6 py-3 rounded-xl font-semibold bg-gradient-to-r from-amber-500 to-orange-500 text-black shadow-lg shadow-amber-500/25 hover:shadow-xl hover:shadow-amber-500/30 hover:scale-[1.02] active:scale-[0.98] transition-all duration-200',
    secondary: 'px-6 py-3 rounded-xl font-semibold bg-slate-800 text-white border border-slate-700 hover:bg-slate-700 hover:border-slate-600 transition-all duration-200',
    ghost: 'px-4 py-2 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800/50 transition-all duration-200',
  },

  // Input styles
  input: {
    base: 'w-full px-4 py-3 rounded-xl bg-slate-800/50 border border-slate-700 text-white placeholder:text-slate-500 focus:border-amber-500 focus:ring-2 focus:ring-amber-500/20 transition-all duration-200',
    error: 'border-red-500 focus:border-red-500 focus:ring-red-500/20',
  },

  // Text styles
  text: {
    gradient: 'bg-gradient-to-r from-white to-slate-300 bg-clip-text text-transparent',
    heading: 'font-bold tracking-tight',
    muted: 'text-slate-400',
  },

  // Layout
  container: 'max-w-7xl mx-auto px-4 sm:px-6 lg:px-8',
  section: 'py-16 md:py-24',
};

export default tokens;
`;

/**
 * Get the design tokens as a file object for injection
 */
export function getDesignTokensFile(): { path: string; content: string; language: string } {
    return {
        path: 'src/lib/design-tokens.ts',
        content: DESIGN_TOKENS_TEMPLATE,
        language: 'typescript',
    };
}

